### ISSUE TITLE
Bot does not create a new channel on new DM

### ISSUE THREAD

**Issue by Doezer** [4rqm/modmail#46]
Got this trace in logs @4rqm  :
2018-07-05T11:46:48.754088+00:00 app[worker.1]: Ignoring exception in on_message
2018-07-05T11:46:48.754278+00:00 app[worker.1]: Traceback (most recent call last):
2018-07-05T11:46:48.754565+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 224, in _run_event
2018-07-05T11:46:48.754568+00:00 app[worker.1]:     yield from coro(*args, **kwargs)
2018-07-05T11:46:48.754612+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-07-05T11:46:48.754614+00:00 app[worker.1]:     await self.process_modmail(message)
2018-07-05T11:46:48.754656+00:00 app[worker.1]:   File "bot.py", line 353, in process_modmail
2018-07-05T11:46:48.754660+00:00 app[worker.1]:     blocked = top_chan.topic.split('Blocked\n-------')[1].strip().split('\n')
2018-07-05T11:46:48.754717+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Doezer** [comment]
Alright, just set it as admin, disabled and re setted it up and it works. Don't know what permissions it's supposed to have anyway...
