### ISSUE TITLE
Setup command not working

### ISSUE THREAD

**Issue by ExDe707** [4rqm/modmail#51]
I'm stuck on the final step. Whenever I DM the bot with the setup command (in my case !setup), it reacts to my message with a check emoji, but does nothing further. This is what I'm getting from the Heroku logs:

```Python
2018-07-29T16:26:23.315324+00:00 app[worker.1]: Ignoring exception in command setup:
2018-07-29T16:26:23.318359+00:00 app[worker.1]: Traceback (most recent call last):
2018-07-29T16:26:23.318526+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 896, in invoke
2018-07-29T16:26:23.318528+00:00 app[worker.1]:     await ctx.command.invoke(ctx)
2018-07-29T16:26:23.318574+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 526, in invoke
2018-07-29T16:26:23.318579+00:00 app[worker.1]:     await self.prepare(ctx)
2018-07-29T16:26:23.318621+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 483, in prepare
2018-07-29T16:26:23.318624+00:00 app[worker.1]:     await self._verify_checks(ctx)
2018-07-29T16:26:23.318668+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 436, in _verify_checks
2018-07-29T16:26:23.318671+00:00 app[worker.1]:     if not (await self.can_run(ctx)):
2018-07-29T16:26:23.318713+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 734, in can_run
2018-07-29T16:26:23.318717+00:00 app[worker.1]:     return (await discord.utils.async_all(predicate(ctx) for predicate in predicates))
2018-07-29T16:26:23.318757+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/utils.py", line 276, in async_all
2018-07-29T16:26:23.318760+00:00 app[worker.1]:     for elem in gen:
2018-07-29T16:26:23.318798+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 734, in <genexpr>
2018-07-29T16:26:23.318801+00:00 app[worker.1]:     return (await discord.utils.async_all(predicate(ctx) for predicate in predicates))
2018-07-29T16:26:23.318839+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/core.py", line 1219, in predicate
2018-07-29T16:26:23.318841+00:00 app[worker.1]:     raise MissingPermissions(missing)
2018-07-29T16:26:23.318906+00:00 app[worker.1]: discord.ext.commands.errors.MissingPermissions: You are missing Administrator permission(s) to run command.
2018-07-29T16:26:23.425442+00:00 app[worker.1]: Ignoring exception in on_message
2018-07-29T16:26:23.425725+00:00 app[worker.1]: Traceback (most recent call last):
2018-07-29T16:26:23.425812+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
2018-07-29T16:26:23.425815+00:00 app[worker.1]:     await coro(*args, **kwargs)
2018-07-29T16:26:23.425860+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-07-29T16:26:23.425862+00:00 app[worker.1]:     await self.process_modmail(message)
2018-07-29T16:26:23.425944+00:00 app[worker.1]:   File "bot.py", line 350, in process_modmail
2018-07-29T16:26:23.425951+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2018-07-29T16:26:23.426017+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'
```

**Comment by fourjr** [comment]
1. Do the command in the server
2. Is your server ID correct?
3. Is the bot in that server?

**Comment by ExDe707** [comment]
1. Done. It set up the server and created a new channel.

2. Yes

3. Yes.

What do I do next?

**Comment by ExDe707** [comment]
People tried DMing it, it reacts to the messages with the tick but doesn't do anything else.

```Python
2018-07-29T16:51:08.080826+00:00 app[worker.1]: Ignoring exception in on_message
2018-07-29T16:51:08.091621+00:00 app[worker.1]: Traceback (most recent call last):
2018-07-29T16:51:08.092261+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 220, in _run_event
2018-07-29T16:51:08.092263+00:00 app[worker.1]:     await coro(*args, **kwargs)
2018-07-29T16:51:08.092398+00:00 app[worker.1]:   File "bot.py", line 379, in on_message
2018-07-29T16:51:08.092400+00:00 app[worker.1]:     await self.process_modmail(message)
2018-07-29T16:51:08.092750+00:00 app[worker.1]:   File "bot.py", line 350, in process_modmail
2018-07-29T16:51:08.092753+00:00 app[worker.1]:     channel = discord.utils.get(guild.text_channels, topic=topic)
2018-07-29T16:51:08.092829+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'text_channels'
```
